### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#112]
The following unit tests are failing:
-CreateReuseDefaultImageDatabas
-DreateUpdateReuseTemplateDatabase
-GenerateControlsAndPropagate

These aren't really failures. Rather, they are due to changes made in the template format and various properties. The solution is to redo some of the code to use the new-style templates. I've already done this with various other unit tests, but the above remain to be done.

Generally, I find that many of the unit tests are incredibly fragile, as they are dependent on a fairly static view of templates (e.g., simple things like tootip names, or more complex things like introducing new controls such as RelativePath, or dropping/adding controls like MarkForDeletion which was replaced by DeleteFlag) (which also leads to differences in how IDs, spreadsheet order, control order are done between old/new template versions). 

To discuss: its likely better to focus the unit tests on logic vs. literals, as maintaining the unit tests becomes painful.

**Comment by twest820** [comment]
Correcting priority as this affects develop.  To repeat reminders given in the past, please adhere to standard checkin gates to keep the code in a healthy state for others; be aware routine practice in multi-programmer projects is to undo commits which break the build or check in tests.

The list of failing tests here is incomplete as these others also fail:
- HybridVideo
- RoundrtripCsv
- Cache
- Exif

Several of these are due to CarnivoreTemplate 2.1.0.4.tdb being missing, suggesting the build is effectively broken in addition to the failure to ensure tests validate state manipulation logic.

There may be additional issues with passing tests firing asserts.

**Comment by saulgreenberg** [comment]
All tests now pass,  file handling presence is repaired, and no asserts are fired.
