### ISSUE TITLE
Timelapse UX: crash on exiting adjustment dialogs

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#119]
When datetimes are adjusted under a custom filter it's possible no images are selected after the adjustments are made.  An unhandled exception in TimelapseWindow.ShowImages() results.  I'm fixing the logic defect---for some reason ShowImages() tries to figure out if any images are selected by looking at ImageCache.CurrentRow instead of the number of selected images---which avoids the crash but results in Constants.Images.EmptyImageSet being displayed.  This is confusing as the user's presented with a display incorrectly stating there are no images in the image set.  So some additional fixing is appropriate, both on this path and on similar cases such as
1. Dark or Ok filter selected, user changes dark threshold
2. Missing or Corrupted filter selected, user deletes the record

Some possible options are
- change the EmptyImageSet .jpg to be general to no images selected as well as no selectable images
- introduce a different resource explaining the currently select filter's run out
- detect the empty selection and revert to All filter
- prompt to change the filter

**Comment by saulgreenberg** [comment]
If I understand this issue correctly, ... The following is the behaviour we want:

CustomFilter should only ever let a person apply the filter only if at least one file matches the query. 

This is the behavior coded into the current release: if 0 files match the query, the Okay button is disabled. Thus it should never get into a situation where there is an empty image set being displayed.

**Comment by saulgreenberg** [comment]
Further investigation reveals a different kind of behaviour related to empty matches that we may want to do something about.
-Apply a custom filter with at least one match (e.g., Sheep > 0, where only one image match).
-Modify those matches so that no images now match (e.g., set Sheep = 0 for that image)
-Try to reapply the custom filter. Because no images now match, its OK button is disabled, which means that the filter state is unchanged (i.e., that no longer matching image remains displayed).

Possible solutions: Put in logic in the custom filter, where:
- when raising the dialog, check the current count. If its zero, set a flag that tells it to revert the filter to All images. 
- If the user resets the filter to some other criteria with a match, user the new criteria
- Otherwise 
              -reset it to all images. 
              - raise a dialog box that states that since no images match the search, 
                 its reverting to all images. Since this is likely a rare occurrence, it shouldn't be
                 too annoying.

**Comment by twest820** [comment]
Proper explanation of empty selection implemented.
