### ISSUE TITLE
build: finishing clearing todos

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#27]
Tracking item for getting through the remaining TODOSAULs in origin/develop and (as of filing this) origin/feature/editor.

**Comment by twest820** [comment]
Bumping priority as this has been sitting for some time and includes CA2241s which will crash Timelapse if those code paths are hit.

**Comment by saulgreenberg** [comment]
Question re: TODOS marked CA2241.
Todd, can you explain further?
CA2241, concerns providing correct arguments to formatting methods, and I don't see an issue to how that is being done e.g., Debug.Assert(false, String.Format("Failure in AddColumn executing query '{0}'."), exception.ToString());

Or perhaps you are referring to how these are used? The methods including the todos marked CA2241 are catches for failures to add/delete/rename columns. While operations are enclosed in a try/catch, I don't expect failure on these, except in really odd conditions that such as  if somehow the database was locked.

Because add/delete/rename columns are usually used for critical operations, there is no really good resolution for those failures except to warn the user and abort Timelapse (which is currently not done, although I could add that).. 

Can you clarify?

**Comment by saulgreenberg** [comment]
Almost all Todos are cleared. 
The few remaining ones are marked ToDo Discretionary.
Likely the only important one is CA1001 (in ImageRow) which should be handled as a separate issue.
