### ISSUE TITLE
images: TimelapseWindow.ShowImage(int, true) bypasses the image cache

### ISSUE THREAD

**Issue by saulgreenberg** [CascadesCarnivoreProject/Carnassial#32]
If a user is displaying a placeholder image for 'Original image no longer available' and the cycles through image differences, it does not return to the missing image. The cycle through combined images then does not work. WHile this would not be an operation that a user would normally do on a missing image, we still have to fix it.

**Comment by twest820** [comment]
If this occurs in the same Timelapse process as the delete did it should be due to this branch in ShowImage() failing to update the unmodified image in the cache, meaning differencing continues to run against the in memory copy of the now deleted image file instead of the placeholder.  If it persists after restart then there's something else going on.

**Comment by twest820** [comment]
[ce4335f]
