### ISSUE TITLE
UX: DialogVideoPlayer refers to a null source as a video

### ISSUE THREAD

**Issue by twest820** [CascadesCarnivoreProject/Carnassial#83]
TimelapseWindow enables the play video menu option for images, meaning DialogVideoPlayer can be popped for them.  Due to #82 this currently results in the confusing message "Video, but Unavailable".  If the user then switches to a video the video dialog continues to display "Video, but Unavailable" rather than showing the video.  This is problematic because
- DialogVideoPlayer is accepting rather than rejecting invalid input from the caller
- DialogVideoPlayer fails to correctly handle input it accepts
- no unit test coverage of DialogVideoPlayer exists which might detect such mainline functionality breaks

**Comment by saulgreenberg** [comment]
I think the issue for this one is the name of the menu item "View the Video" - I will change it to "Show Video Player". The intent is that the user can raise the video player at any time, regardless of whether they are on a video or image, as they can then navigate through both images and video. 

However, I could not replicate the actual messages you are describing. When I open the video player on an image, it shows 'Image, not Video' (you say it shows (Video, but Unavailable). Even so, I will fix 82 and test it.

The Video, but Unavailable should only show when the user had deleted the video but kept the data (i.e., the video is missing). I will change the message to make that clearer.

Another option - which I had in a test version, is to show the jpg for images rather than the 'Image, not video' message. But I decided to use the message instead as I wanted the user to be able to scroll through and rapidly discern between files that were images vs videos.

Note that this video player is temporary - I will be removing it in a future version where the video plays in the main screen automatically.

**Comment by saulgreenberg** [comment]
Unit test not added at this point as this video player will be replaced in (hopefully near-term) releases.
